source 'https://rubygems.org'

gem 'coffee-rails', '~> 4.1.0'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'rails', '4.2.5'
gem 'sass-rails', '~> 5.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'sqlite3'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'

group :development, :test do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'pry'
  gem 'pry-rails'
  gem 'quiet_assets'
  gem 'rspec-core'
  gem 'rspec-json_expectations'
  gem 'rspec-rails', '~> 3.5'
  gem 'rspec-support'
  gem 'rubocop', require: false
  gem 'shoulda-matchers', '~> 3.1'
  gem 'simplecov', require: false
  gem 'simplecov-rcov'
  gem 'spring-commands-rspec'
end

group :development do
  gem 'spring'
  gem 'web-console', '~> 2.0'
end
